export enum StatutProbleme {
  NOUVEAU = "NOUVEAU",
  EN_ATTENTE_EVALUATION = "EN_ATTENTE_EVALUATION",
  EN_COURS_ENQUETE = "EN_COURS_ENQUETE",
  EN_COURS_RESOLUTION = "EN_COURS_RESOLUTION",
  RESOLU = "RESOLU"
}
